Repository Jonxslays/unkey, pull requests merged in 2023-08, with the labels that each got.

#10 Add missing fields to verify key response and logging
  src/client.rs
  src/lib.rs
  src/logging.rs
  src/models/keys.rs
  src/services/http.rs
Labels: enhancement

#13 Update github templates and docstring changes
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/others.yml
  .github/pull_request_template.md
  .github/workflows/ci.yml
  src/client.rs
  src/models/apis.rs
  src/services/apis.rs
Labels: documentation

#15 Refactor client and service methods to all accept a request struct
  .github/pull_request_template.md
  src/client.rs
  src/lib.rs
  src/logging.rs
  src/models/apis.rs
  src/models/keys.rs
  src/models/mod.rs
  src/models/ratelimit.rs
  src/routes.rs
  src/services/apis.rs
  src/services/http.rs
  src/services/keys.rs
  src/types.rs
Labels: enhancement

#16 Implement logging macros
  src/lib.rs
  src/logging.rs
  src/services/http.rs
Labels: enhancement

#17 Refactor module visibility
  .github/workflows/ci.yml
  src/client.rs
  src/lib.rs
  src/models/http.rs
  src/models/mod.rs
  src/routes.rs
  src/services/apis.rs
  src/services/http.rs
  src/services/keys.rs
  src/services/mod.rs
Labels: enhancement

#18 Improve DX around fetch payloads
  src/lib.rs
  src/services/apis.rs
  src/services/keys.rs
Labels: enhancement

#19 Implement revoke key
  CHANGELOG.md
  src/client.rs
  src/lib.rs
  src/models/keys.rs
  src/routes.rs
  src/services/apis.rs
  src/services/keys.rs
Labels: enhancement

#21 Implement get api
  CHANGELOG.md
  src/client.rs
  src/models/apis.rs
  src/routes.rs
  src/services/apis.rs
Labels: enhancement

#22 Unpin serde
  Cargo.toml
Labels: random

#24 Implement update key
  CHANGELOG.md
  src/client.rs
  src/lib.rs
  src/models/keys.rs
  src/routes.rs
  src/services/keys.rs
  src/undefined.rs
Labels: enhancement

#25 Improve `UndefinedOr` and tests
  src/client.rs
  src/lib.rs
  src/models/apis.rs
  src/models/http.rs
  src/models/keys.rs
  src/models/ratelimit.rs
  src/services/apis.rs
  src/services/keys.rs
  src/undefined.rs
Labels: enhancement, testing

#26 Add documentation for remaining public api
  README.md
  src/lib.rs
  src/logging.rs
  src/models/keys.rs
  src/models/mod.rs
  src/models/undefined.rs
Labels: documentation, enhancement
